apiVersion: v1
kind: ConfigMap
metadata:
   name: task-app-config
   namespace: task-app
data:
  DB_HOST: postgres-service
  DB_PORT: "5432"
  DB_NAME: taskdb
  DB_USER: postgres
  CORS_ORIGINS: "http://task-app.local"
  FLASK_ENV: production

